version: '2'
services:
  web:
    image: nginx:alpine
    container_name: nginx-funds
    ports:
      - 80:80
    volumes:
      - ./web-app:/web
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./logs:/web/logs
